
services:
  nginx:
    image: luslucifer490587/vidjoy-nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - vidjoy

  proxy-server:
    image: luslucifer490587/vidjoy-proxy-server:latest
    expose:
      - 80
    networks:
      - vidjoy
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - PROTOCOL=https
      - CORSANYWHERE_WHITELIST=https://moviekex.com,https://developer-tools.jwplayer.com,https://yestream.vidsrc.nl
    command: "npm run start"

  server:
    image: luslucifer490587/vidjoy-server:latest
    expose:
      - 80
    networks:
      - vidjoy
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - PROTOCOL=https
    command: "npm run start"

  frontend:
    image: luslucifer490587/vidjoy-frontend:latest
    restart: unless-stopped
    expose:
      - 5173
    networks:
      - vidjoy
    ports:
      - 5170:3000
    environment:
      - PROTOCOL=http
      - TMDB_KEY=${TMDB_KEY}
    command: "npm run start"

  sub:
    image: luslucifer490587/vidjoy-sub:latest
    restart: always
    networks:
      - vidjoy
    environment:
      - PORT=80
      - TMDB_KEY=${TMDB_KEY}
      - PROTOCOL=https
    command: "bun run start"

  thumb:
    image: luslucifer490587/vidjoy-thumb:latest
    restart: always
    networks:
      - vidjoy
    environment:
      - PORT=80
      - TMDB_KEY=${TMDB_KEY}
      - PROTOCOL=https
    command: "npm run start"

  redis:
    image: redis/redis-stack:latest
    expose:
      - 8001
      - 6379
    networks:
      - vidjoy

  # Watchtower service for auto-updating all containers every 5 minutes
  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vidjoy
    environment:
      - WATCHTOWER_CLEANUP=true        # Automatically remove old images
      - WATCHTOWER_POLL_INTERVAL=300   # Check every 5 minutes (300 seconds)
    command: --interval 300 --cleanup  # Interval and cleanup flag

networks:
  vidjoy:
    driver: bridge
