version: '3.8'

services:
  nginx:
    image: 'luslucifer490587/vidjoy-nginx:latest' 
    build: ./nginx
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    # volumes:
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx/letsencrypt:/etc/letsencrypt
      # - ./nginx/html:/usr/share/nginx/html
      # - ./nginx/logs:/var/log/nginx
    networks:
      - vidjoy

  proxy-server:
    image: luslucifer490587/vidjoy-proxy-server:latest
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - PUBLIC_URL=http://localhost/proxy/
      - NODE_ENV=production
    networks:
      - vidjoy
    expose:
      - 80
    command: "npm start"

  server:
    image: luslucifer490587/vidjoy-server:latest
    restart: unless-stopped
    environment:
      - HOST=0.0.0.0
      - PORT=80
      - NODE_ENV=production
    networks:
      - vidjoy
    expose:
      - 80
    command: "npm start"

  player: 
    image: luslucifer490587/vidjoy-player:latest
    restart: unless-stopped
    expose:
      - 5173
    networks:
      - vidjoy
    ports:
      - 5173:5173
    # command: "npm start"

  redis: 
    image: redis/redis-stack:latest
    restart: unless-stopped
    expose:
      - 8001
      - 6379
    networks:
      - vidjoy

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_POLL_INTERVAL=300  # Check for updates every 300 seconds (5 minutes)
    networks:
      - vidjoy

networks:
  vidjoy: 
    driver: bridge
