version: "3.8"

services:
  nginx:
    image: luslucifer490587/vidjoy-nginx:latest
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    networks:
      - vidjoy

  proxy-server:
    image: luslucifer490587/vidjoy-proxy-server:latest
    expose:
      - 80
    networks:
      - vidjoy
    restart: unless-stopped
    env_file:
      - .env  # Loads environment variables from the .env file
    command: "npm run start"

  server:
    image: luslucifer490587/vidjoy-server:latest
    expose:
      - 80
    networks:
      - vidjoy
    restart: unless-stopped
    env_file:
      - .env  # Loads environment variables from the .env file
    command: "npm run start"

  frontend:
    image: luslucifer490587/vidjoy-frontend:latest
    restart: unless-stopped
    expose:
      - 5173
    networks:
      - vidjoy
    ports:
      - 5170:3000
    env_file:
      - .env  # Loads environment variables from the .env file
    command: "npm run start"

  sub:
    image: luslucifer490587/vidjoy-sub:latest
    restart: always
    networks:
      - vidjoy
    env_file:
      - .env  # Loads environment variables from the .env file
    command: "bun run start"

  thumb:
    image: luslucifer490587/vidjoy-thumb:latest
    restart: always
    networks:
      - vidjoy
    env_file:
      - .env  # Loads environment variables from the .env file
    command: "npm run start"

  redis:
    image: redis/redis-stack:latest
    expose:
      - 8001
      - 6379
    networks:
      - vidjoy

  vidjoy-webapp:
    image: luslucifer490587/vidjoy-webapp
    ports:
      - 3002:3000
    env_file:
      - .env  # Loads environment variables from the .env file
    networks:
      - vidjoy
    command: "npm run start"

  portainer:
    image: portainer/portainer-ce:2.21.4
    container_name: portainer
    restart: always
    ports:
      - "8000:8000"
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vidjoy

  watchtower:
    image: containrrr/watchtower:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - vidjoy
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=300
    command: --interval 300 --cleanup

networks:
  vidjoy:
    driver: bridge
